from src.models import Doctor
from src.models import Secretary
from src.models import LabUser
from src.models import ExecutiveUser
from src.models import Patient
from src.models import Address
from src.models import Appointment
from src.models import Item
from src.models import Medicine
from src.models import Prescription
from src.models import Sample
